# Generated by Django 5.2.5 on 2025-08-25 00:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='receta',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='alergias',
            field=models.CharField(blank=True, help_text='Lista separada por comas', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='categorias',
            field=models.CharField(blank=True, help_text='Lista separada por comas', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receta',
            name='dificultad',
            field=models.CharField(choices=[('Fácil', 'Fácil'), ('Intermedio', 'Intermedio'), ('Difícil', 'Difícil')], default='Fácil', max_length=20),
        ),
        migrations.AddField(
            model_name='receta',
            name='porciones',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='tiempo',
            field=models.PositiveIntegerField(blank=True, help_text='Tiempo en minutos', null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receta',
            name='ingredientes',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='receta',
            name='instrucciones',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='receta',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
